name: edgerlhf
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11

  # Core ML/DL
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8

  # Scientific Computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - scipy>=1.10.0

  # Jupyter Environment
  - jupyter
  - ipykernel
  - ipywidgets
  - jupyterlab

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # Utilities
  - tqdm
  - pyyaml
  - psutil
  - requests

  # Development Tools
  - git
  - pre-commit
  - black
  - flake8

  # pip dependencies
  - pip
  - pip:
    # HuggingFace ecosystem
    - transformers>=4.50.0
    - datasets>=3.0.0
    - accelerate>=0.20.0
    - peft>=0.8.0
    - trl>=0.19.0
    - safetensors>=0.4.0
    
    # Quantization
    - bitsandbytes>=0.46.0
    
    # Optional: Experiment tracking (uncomment if needed)
    # - wandb>=0.15.0
    # - tensorboard>=2.15.0
    
    # Development
    - pytest
    - pytest-cov 